accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('',views.login_view,name='login'),
    path('logout/',views.logout_view, name="logout")
]

admins/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from calendars import views as cal_views

app_name = "admins"

urlpatterns = [
    path('signup/',views.signup_view,name='home'),
    path('standard_list',views.standard_list_view,name='standard_list'),
    path('student_list/<slug:slug>/',views.student_list_view,name='student_list'),
    path('all_student_list/',views.all_student_list,name='all_student_list'),
    path('all_teacher_list/',views.all_teacher_list,name='all_teacher_list'),
    path('student_update/<slug:slug>/',views.student_update_view,name='student_update'),
    path('teacher_update/<slug:slug>/',views.teacher_update_view,name='teacher_update'),
    path('refresh_standard/<slug:slug>/',views.refresh_standard_view,name='refresh_standard'),
    path('subject_list/<slug:slug>/',views.subject_list_view,name='subject_list'),
    path('subject_update/<slug:slug>/',views.subject_update_view,name='subject_update'),
    path('class_teacher_update/<slug:slug>/',views.class_teacher_update,name='class_teacher_update'),
    path('student_profile/<slug:slug>/',views.student_profile_view,name='student_profile'),
    path('teacher_profile/<slug:slug>/',views.teacher_profile_view,name='teacher_profile'),

    path('calendar/',cal_views.admin_calendar,name='calendar'),
    path('event/new/',cal_views.event,name='event_new'),
    path('event/edit/<slug:slug>/',cal_views.event, name="event_edit"),
    path('event/delete/<slug:slug>/',cal_views.event_delete, name="event_delete"),
    
]

calendars/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'calendars'

urlpatterns = [
    
]

myschool/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('db/', admin.site.urls),
    path('',include('accounts.urls')),
    path('teacher/',include('teachers.urls')),
    path('student/',include('students.urls')),
    path('admin/',include('admins.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

calendars/models.py
from django.db import models
from django.urls import reverse
from django.db.models.signals import post_save, pre_save
from accounts.utils import unique_email_slug_generator
from accounts.models import User

class Event(models.Model):
    title = models.CharField(max_length=200)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    broadcast = models.BooleanField(default=False)
    slug = models.SlugField(max_length=210,blank=True,null=True,editable=False)

    @property
    def get_html_url(self):
        url = reverse('students:event_edit', args=(self.slug,))
        return f"<a href={url}> {self.title} (self) </a>"

def slug_generator(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_email_slug_generator(instance)

pre_save.connect(slug_generator,sender=Event)

calendars/forms.py
from django.forms import ModelForm, DateInput, CheckboxInput
from .models import Event

class EventForm(ModelForm):
  class Meta:
    model = Event
    # datetime-local is a HTML5 input type, format to make date time show on fields
    widgets = {
      'start_time': DateInput(attrs={'type': 'datetime-local','placeholder': 'yyyy-mm-ddThh:mm (Ex: 2001-01-31T20:56)'}, format='%Y-%m-%dT%H:%M'),
      'end_time': DateInput(attrs={'type': 'datetime-local','placeholder': 'yyyy-mm-ddThh:mm (Ex: 2001-01-31T20:58)'}, format='%Y-%m-%dT%H:%M'),
      'broadcast': CheckboxInput(attrs={'class':'broadcast'})
    }
    exclude = ('user',)

  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    # input_formats to parse HTML5 datetime-local input to datetime field
    self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
    self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

calendars/views.py
from datetime import datetime, timedelta, date
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
import calendar

from .models import *
from .utils import Calendar
from .forms import EventForm

class CalendarView(generic.ListView):
    model = Event
    template_name = 'students/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # use today's date for the calendar
        d = get_date(self.request.GET.get('month', None))

        # Instantiate our calendar class with today's year and date
        cal = Calendar(d.year, d.month, self.request.user)

        # Call the formatmonth method, which returns our calendar as a table
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

@login_required
def student_calendar(request):
    if not request.user.is_student:
        return HttpResponse("<h1>UNAUTHORISED</h1>")
    d = get_date(request.GET.get('month', None))
    cal = Calendar(d.year, d.month, request.user)
    html_cal = cal.formatmonth(withyear=True)
    context={}
    context['calendar'] = mark_safe(html_cal)
    context['prev_month'] = prev_month(d)
    context['next_month'] = next_month(d)
    return render(request,"students/calendar.html",context)

@login_required
def admin_calendar(request):
    if not request.user.is_admin:
        return HttpResponse("<h1>UNAUTHORISED</h1>")
    d = get_date(request.GET.get('month', None))
    cal = Calendar(d.year, d.month, request.user)
    html_cal = cal.formatmonth(withyear=True)
    context={}
    context['calendar'] = mark_safe(html_cal)
    context['prev_month'] = prev_month(d)
    context['next_month'] = next_month(d)
    return render(request,"admins/calendar.html",context)


def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

@login_required
def event(request, slug=None):
    instance = Event()
    if slug:
        type = 'delete'
        instance = Event.objects.get(slug=slug)
        if not request.user.is_admin and instance.user != request.user:
            return HttpResponse("<h1>UNAUTHORISED</h1>")
    else:
        type = None
        instance = Event()

    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        event = form.save(commit=False)
        event.user = request.user
        event.save()
        if request.user.is_admin:
            return redirect('admins:calendar')
        if request.user.is_student:
            return redirect('students:calendar')
    if request.user.is_admin:
        return render(request,'admins/event.html',{'form':form,'type':type,'slug':slug})
    if request.user.is_student:
        return render(request, 'students/event.html', {'form': form,'type':type,'slug':slug})

@login_required
def event_delete(request, slug):
    instance = Event.objects.get(slug=slug)
    if not request.user.is_admin and instance.user != request.user:
        return HttpResponse("<h1>UNAUTHORISED</h1>")

    instance.delete()

    if request.user.is_admin:
        return redirect('admins:calendar')
    if request.user.is_student:
        return redirect('students:calendar')

templates/admins/all_student_list.html
{% extends 'admins/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'admins/style.css' %}">
{% endblock %}

{% block body_block %}
<hr class='hr-text' data-content="View Student's Profile"> <br>
<div class="container">
    <form class="student-list-form" method="post">
      {% csrf_token %}
      <label for="students">Student email: </label>
      <input type="email" class="form-control" list="student-emails" id="students" name="stud">
      <datalist id="student-emails">
        {% for student in students %}
            <option value="{{student}}">{{student.user.get_full_name}}</option>
        {% endfor %}
      </datalist> <br>
      <input class="btn btn-primary btn-block" type="submit" name="submit" value="View student profile">
    </form>
</div>
{% endblock %}

templates/admins/all_teacher_list.html
{% extends 'admins/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'admins/style.css' %}">
{% endblock %}

{% block body_block %}
<hr class='hr-text' data-content="View Teacher's Profile"> <br>
<div class="container">
    <form class="student-list-form" method="post">
      {% csrf_token %}
      <label for="teachers">Teacher email: </label>
      <input type="email" class="form-control" list="teacher-emails" id="teachers" name="stud">
      <datalist id="teacher-emails">
        {% for teacher in teachers %}
            <option value="{{teacher.user.email}}">{{teacher.user.get_full_name}}</option>
        {% endfor %}
      </datalist> <br>
      <input class="btn btn-primary btn-block" type="submit" name="submit" value="View teacher's profile">
    </form>
  </div>
</div>
{% endblock %}

templates/admins/base.html
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Admin</title>
    <link rel="stylesheet" href="{% static 'general.css' %}">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
    crossorigin="anonymous">
  {% block stylesheets %}
  {% endblock %}
</head>
<body>
  <!-- <img class="logo" src="{% static 'images/fchs.png' %}" alt=""> -->

    <nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-primary">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#" style="cursor:auto;">Hello ADMIN</a>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'admins:home' %}">Signup <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'admins:standard_list' %}">Standards</a>
          </li>
          <!-- <li class="nav-item active">
            <a class="nav-link" href="#">Rare Operations</a>
          </li> -->
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'admins:all_student_list' %}">View Student's Profile</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'admins:all_teacher_list' %}">View Teacher's Profile</a>
          </li>
          <!-- <li class="nav-item active">
            <a class="nav-link" href="#">Update subjects</a>
          </li> -->
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'admins:calendar' %}">Calendar</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'accounts:logout'%}">Logout</a>
          </li>
        </ul>
      </div>
    </nav>
    <br> 

  {% block body_block %}
  {% endblock %}

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
   crossorigin="anonymous"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
   crossorigin="anonymous"></script>
</body>
</html>

templates/admins/calendar.html
{% extends 'admins/base.html' %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'calendars/style.css' %}">
{% endblock %}

{% block body_block %}
<hr class='hr-text' data-content="My Calendar">  <br>
<div class="clearfix">
	<a class="btn btn-info left" href="{% url 'admins:calendar' %}?{{ prev_month }}"> Previous Month </a>
	<a class="btn btn-info right" href="{% url 'admins:calendar' %}?{{ next_month }}"> Next Month </a>
	<a class="btn btn-info right" href="{% url 'admins:event_new' %}"> New Event </a>
</div>
{{ calendar }}
{% endblock %}

templates/admins/class_teacher_update.html
{% extends 'admins/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'admins/style.css' %}">
{% endblock %}

{% block body_block %}
<br>
<div class="container">
  <div class="jumbotron">
    <h3 style="text-align: center; font-weight: bold; text-decoration: underline;">Class Teacher Update:</h3> <br> 
    <p> <strong>Standard: </strong>{{class_teacher.standard|title}}</p><br>
    <form class="student-list-form" method="post">
      {% csrf_token %}
      {{form|crispy}}
      <input class="btn btn-primary btn-block" type="submit" name="submit" value="Submit">
    </form>
  </div>
</div>
{% endblock %}

templates/admins/event.html
{% extends 'admins/base.html' %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'calendars/style.css' %}">
<style media="screen">
  .broadcast {
    display: block;
    float: right;
  }
</style>
{% endblock %}

{% block body_block %}
  <hr class='hr-text' data-content="New event">  
  <div class="clearfix">
    <a class="btn btn-info left" href="{% url 'admins:calendar' %}"> Calendar </a>
  </div>

  {% if form.errors %}
      {% for field in form %}
          {% for error in field.errors %}
              <div class="alert alert-danger">
                  {{ field.label }} <strong>{{ error|escape }}</strong>
              </div>
          {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
              {{ field.label }} <strong>{{ error|escape }}</strong>
          </div>
      {% endfor %}
  {% endif %}

  <form method="post">
    {% csrf_token %}
    <table class="form form-table">
      {{form}}
      <tr>
        <td colspan="2">
          <button type="submit" class="btn btn-info left"> Submit </button>
        </td>
        {% if type is not None %}
        <td colspan="2">
          <a href="{% url 'admins:event_delete' slug=slug %}" class="btn btn-info right"> Delete </a>
        </td>
        {% endif %}
      </tr>
    </table>
  </form>
{% endblock %}

templates/admins/refresh_standard.html
{% extends 'admins/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'admins/style.css' %}">
{% endblock %}

{% block body_block %}
<hr class='hr-text' data-content="Standard: {{standard}}"> <br>
<div class="container jumbotron" style="padding: 20px 30px;">
    <form class="student-list-form" method="post">
      {% csrf_token %}
      {{form|crispy}}
      <input class="btn btn-primary btn-block" type="submit" name="submit" value="Submit">
    </form>
  </div>
</div>
{% endblock %}

templates/admins/standard_list.html
{% extends 'admins/base.html' %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'admins/style.css' %}">
{% endblock %}

{% block body_block %}
<hr class='hr-text' data-content="Standards"> <br>
<div class="container">
    <div data-spy="scroll" class="container panel-body">
      <table class="upload-table table student-update-table thead-dark table-hover table-bordered"
              style="text-align:center;">
        <tr>
          <th>Standard</th>
          <th>StudentList</th>
          <th>SubjectList</th>
          <th>Class Teacher (Click to update)</th>
        </tr>
        {% for standard in standards %}
        <tr>
          <td>{{standard}}</td>
          <td>
            <a class="" href="{% url 'admins:student_list' slug=standard.slug %}">List of students</a>
          </td>
          <td>
            <a class="" href="{% url 'admins:subject_list' slug=standard.slug %}">List of subjects</a>
          </td>
          <td>
            <a class="" href="{% url 'admins:class_teacher_update' slug=standard.slug %}">{{standard.class_teacher.teacher}}</a>
          </td>
        </tr>
        {% endfor %}
      </table>
    </div>
  </div>
{% endblock %}

templates/admins/student_profile.html
{% extends 'admins/base.html' %}
{% load static %}

{% block stylesheets %}
  <link rel="stylesheet" href="{% static 'students/style.css' %}">
{% endblock %}

{% block body_block%}
  <div class="container profile-box">
    <h4>Student Profile</h4>
    <table class="table thead-dark table-hover table-borderless">
      <tr>
        <td><strong>Student name:</strong></td>
        <td>{{student.user.first_name}} {{student.user.last_name}}</td>
      </tr>
      <tr>
        <td><strong>Email:</strong></td>
        <td>{{student.user.email}}</td>
      </tr>
      <tr>
        <td><strong>Permanent Address:</strong></td>
        <td>{% if student.user.address %}
              {{student.user.address}}
            {% endif %}\</td>
      </tr>
      <tr>
        <td><strong>Date of birth:</strong></td>
        <td>{% if student.user.date_of_birth %}
              {{student.user.date_of_birth}}
            {% endif %}</td>
      </tr>
      <tr>
        <td><strong>Father's Name:</strong></td>
        <td>{% if student.father %}
          {{student.father}}
        {% endif %}</td>
      </tr>
      <tr>
        <td><strong>Contact:</strong></td>
        <td>{{student.user.contact_no}}</td>
      </tr>
      <tr>
        <td><strong>Standards:</strong></td>
      </tr>
      <tr>
        <td><strong>Current standard:</strong></td>
        <td>{{student.current_standard}}</td>
      </tr>
      <tr>
        <td><strong>Roll No:</strong></td>
        <td>{{student.roll_number}}</td>
      </tr>
      <tr>
        <td><strong>Caste:</strong></td>
        <td>{{student.caste}}</td>
      </tr>
      <tr>
        <td><strong>Religion:</strong></td>
        <td>{{student.religion}}</td>
      </tr>
      <tr>
        <td><strong>Profile picture:</strong></td>
        {% if student.user.profile_pic %}
        <td><img src="{{student.user.profile_pic.url}}"
                 alt="No profile pic"
                 style="width:150px; height:150px; margin-bottom:5px"><br>
        {% else %}
        <td>
          <img src="{% static 'images/default_profile_pic.png' %}"
               alt=""
               style="width:150px; height:150px"><br>
        {% endif %}
        </td>
      </tr>
      <tr>
        <td colspan="2" style="text-align: center;">
          <a class="btn btn-success" href="{% url 'admins:student_update' slug=student.slug %}">Update Profile</a>
        </td>
      </tr>
    </table>
  </div>
{% endblock %}

templates/admins/student_update.html
{% extends 'admins/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'admins/style.css' %}">
{% endblock %}

{% block body_block %}
<hr class='hr-text' data-content="Update Student's Profile"> <br>
<div class="container jumbotron" style="padding: 20px 30px;">
    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{userform|crispy}}
      {{form|crispy}}
      <input class="btn btn-primary btn-block" type="submit" name="submit" value="Submit">
    </form>
</div>
{% endblock %}

templates/admins/subject_list.html
{% extends 'admins/base.html' %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'admins/style.css' %}">
{% endblock %}

{% block body_block %}
<br><br>
<div class="container">
    <div data-spy="scroll" class="container panel-body">
      <table class="upload-table table student-update-table thead-dark table-hover table-bordered"
              style="text-align:center;">
        <tr>
          <td colspan="4" style="color:white;background-color:#2075d8;">
            <h3 style="font-weight:bold">Standard-{{standard}} : List of subjects</h3>
          </td>
        </tr>
        <tr>
          <td></td>
        </tr>
        <tr>
          <th>S.No</th>
          <th>Subject</th>
          <th>Teacher (Click to update teacher profile)</th>
          <th>Update</th>
        </tr>
        {% for subject in subjects %}
        <tr>
          <td>{{forloop.counter}}</td>
          <td>
            <p>{{subject|title}}</p>
          </td>
          <td>
            <a class="" href="{% url 'admins:teacher_update' slug=subject.teacher.slug %}">{{subject.teacher}}</a>
          </td>
          <td>
            <a class="btn btn-success" href="{% url 'admins:subject_update' slug=subject.slug %}">Update</a>
          </td>
        </tr>
        {% endfor %}
      </table>
    </div>
  </div>
{% endblock %}

templates/admins/subject_teacher_update.html
{% extends 'admins/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'admins/style.css' %}">
{% endblock %}

{% block body_block %}
<br>
<div class="container">
  <div class="jumbotron">
    <h3 style="text-align: center; font-weight: bold; text-decoration: underline;">Subject Teacher Update:</h3> <br> 
    <p> <strong>Subject: </strong> {{subject|title}}</p><br>
    <p> <strong>Standard: </strong>{{subject.standard|title}}</p><br>
    <form class="student-list-form" method="post">
      {% csrf_token %}
      {{form|crispy}}
      <input class="btn btn-primary" type="submit" name="submit" value="Submit">
    </form>
  </div>
</div>
{% endblock %}

templates/admins/teacher_profile.html
{% extends 'admins/base.html' %}
{% load static %}

{% block stylesheets %}
  <link rel="stylesheet" href="{% static 'students/style.css' %}">
{% endblock %}

{% block body_block %}
  <div class="container profile-box">
      <h4>Teacher Profile</h4>
    <table class="table thead-dark table-hover table-borderless" style="text-align:left">
      <tr>
        <td><strong>Teacher name:</strong></td>
        <td>{{teacher.user.get_full_name}}</td>
      </tr>
      <tr>
        <td><strong>Email:</strong></td>
        <td>{{teacher.user.email}}</td>
      </tr>
      <tr>
        <td><strong>Date of birth:</strong></td>
        <td>{% if teacher.user.date_of_birth %}
              {{teacher.user.date_of_birth}}
            {% endif %}</td>
      </tr>
      <tr>
        <td><strong>Contact no:</strong></td>
        <td>{% if teacher.user.contact_no %}
              {{teacher.user.contact_no}}
            {% endif %}</td>
      </tr>
      <tr>
        <td><strong>Permanent Address:</strong></td>
        <td>{% if teacher.user.address %}
              {{teacher.user.address}}
            {% endif %}</td>
      </tr>
      <tr>
        <td><strong>Currently teaching:</strong></td>
        <td>
          {% for subject in subjects %}
            {{subject|title}} to Standard: {{subject.standard}} <br>
          {% endfor %}
        </td>
      </tr>
      <tr>
        <td><strong>Profile picture:</strong></td>
        {% if teacher.user.profile_pic %}
        <td><img src="{{teacher.user.profile_pic.url}}"
                 alt="No profile pic"
                 style="width:150px; height:150px; margin-bottom:5px"><br>
        {% else %}
        <td>
          <img src="{% static 'images/default_profile_pic.png' %}"
               alt=""
               style="width:150px; height:150px"><br>
        {% endif %}
        </td>
      </tr>
      <tr>
        <td colspan="2" style="text-align: center;">
          <a class="btn btn-success" href="{% url 'admins:teacher_update' slug=teacher.slug %}">Update Profile</a>
        </td>
      </tr>
    </table>
    </div>
  </div>
{% endblock %}

templates/admins/teacher_update.html
{% extends 'admins/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'admins/style.css' %}">
{% endblock %}

{% block body_block %}
<hr class='hr-text' data-content="Update Teacher's Profile"> <br>
<div class="container jumbotron" style="padding: 20px 30px;">
    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{userform|crispy}}
      {{form|crispy}}
      <input class="btn btn-primary btn-block" type="submit" name="submit" value="Submit">
    </form>
</div>
{% endblock %}