accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('',views.login_view,name='login'),
    path('logout/',views.logout_view, name="logout")
]

admins/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from calendars import views as cal_views

app_name = "admins"

urlpatterns = [
    path('signup/',views.signup_view,name='home'),
    path('standard_list',views.standard_list_view,name='standard_list'),
    path('student_list/<slug:slug>/',views.student_list_view,name='student_list'),
    path('all_student_list/',views.all_student_list,name='all_student_list'),
    path('all_teacher_list/',views.all_teacher_list,name='all_teacher_list'),
    path('student_update/<slug:slug>/',views.student_update_view,name='student_update'),
    path('teacher_update/<slug:slug>/',views.teacher_update_view,name='teacher_update'),
    path('refresh_standard/<slug:slug>/',views.refresh_standard_view,name='refresh_standard'),
    path('subject_list/<slug:slug>/',views.subject_list_view,name='subject_list'),
    path('subject_update/<slug:slug>/',views.subject_update_view,name='subject_update'),
    path('class_teacher_update/<slug:slug>/',views.class_teacher_update,name='class_teacher_update'),
    path('student_profile/<slug:slug>/',views.student_profile_view,name='student_profile'),
    path('teacher_profile/<slug:slug>/',views.teacher_profile_view,name='teacher_profile'),

    path('calendar/',cal_views.admin_calendar,name='calendar'),
    path('event/new/',cal_views.event,name='event_new'),
    path('event/edit/<slug:slug>/',cal_views.event, name="event_edit"),
    path('event/delete/<slug:slug>/',cal_views.event_delete, name="event_delete"),
    
]

myschool/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('db/', admin.site.urls),
    path('',include('accounts.urls')),
    path('teacher/',include('teachers.urls')),
    path('student/',include('students.urls')),
    path('admin/',include('admins.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teachers/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from uploads import views as upload_views

app_name = 'teachers'

urlpatterns = [
    path('home/',views.TeacherTemplateView.as_view(),name='home'),
    path('profile/<slug:slug>/',views.teacher_profile_view,name='profile'),
    # path('calendar/',calendars.views.CalendarView.as_view(),name='calendar'),
    path('update_result/<slug:slug>/',views.class_result_update,name='update_result'),
    path('upload/<slug:slug>/',upload_views.upload_view,name='upload'),
    path('upload/delete/<slug:slug>/',upload_views.delete_view,name='delete_upload'),
    path('class_teacher_home/',views.class_teacher_home,name="class_teacher_home"),
    path('profile_pic_update/',views.profile_pic_update_view,name='profile_pic_update'),

    path('class_teacher/student_grade/<slug:slug>/',views.student_grade_view,name="student_grade")
]

teachers/models.py
from django.db import models
from accounts.models import User
from accounts.utils import unique_email_slug_generator
from django.db.models.signals import pre_save

class Teacher(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,null=True,related_name="teacher")
    created_at = models.DateTimeField(auto_now_add=True,editable=False)
    updated_at = models.DateTimeField(auto_now=True,editable=False)
    slug = models.SlugField(max_length=210,blank=True,null=True, editable=False)

    class Meta:
        default_related_name = 'teachers'

    def __str__(self):
        return self.user.get_full_name()

def slug_generator(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_email_slug_generator(instance)

pre_save.connect(slug_generator,sender=Teacher)


# from django.db.models.signals import post_save
# from django.dispatch import receiver

# @receiver(post_save, sender=auth_User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         Teacher.objects.create(user=instance)
#
# @receiver(post_save, sender=auth_User)
# def save_user_profile(sender, instance, **kwargs):
#     instance.profile.save()

uploads/models.py
from django.db import models
from subjects.models import Subject
from .validators import validate_file_extension
from accounts.utils import unique_email_slug_generator
from django.db.models.signals import pre_save

TYPE_CHOICES = (
    ("Assignment","Assignment"),
    ("Notice","Notice"),
    ("Announcement","Announcement"),
    ("Reference","Reference"),
    ("Marksheet","Marksheet")
)

class Upload(models.Model):
    title = models.CharField(max_length=100)
    subject = models.ForeignKey(Subject,on_delete=models.CASCADE,null=True)
    type = models.CharField(max_length=20,
                           choices=TYPE_CHOICES,
                           default="Assignment")
    pdf = models.FileField(upload_to="uploads/",
                           validators=[validate_file_extension])
    timestamp = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=210,blank=True,null=True, editable=False)

    def __str__(self):
        return self.title

    def delete(self,*args,**kwargs):
        self.pdf.delete()
        super().delete(*args,**kwargs)

import string
import random
from django.utils.text import slugify

def random_string_generator(size=10, chars=string.ascii_lowercase+string.digits):
    return ''.join(random.choice(chars) for _ in range(size))

def unique_slug_generator(instance,new_slug=None):
    if new_slug is not None:
        slug = new_slug
    else:
        slug = slugify(instance.title)

    mod = instance.__class__
    qs_exists = mod.objects.filter(slug=slug).exists()
    if qs_exists:
        new_slug = "{}-{}".format(slug,random_string_generator(size=4))
        return unique_slug_generator(instance,new_slug)
    return slug

def slug_generator(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(slug_generator,sender=Upload)

teachers/forms.py
from django import forms

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

uploads/forms.py
from django import forms
from .models import Upload

class UploadForm(forms.ModelForm):
    class Meta:
        model = Upload
        fields = ('title','type','pdf')

teachers/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import (TemplateView,ListView,
                                  DetailView, CreateView,
                                  UpdateView, DeleteView)
from django.contrib.auth import authenticate, get_user_model, login
from django.core.files.storage import FileSystemStorage

from students.models import Student
from results.models import Result, Examination
from teachers.models import Teacher
from subjects.models import Subject
from standards.models import Standard, ClassTeacher
from accounts.models import User

from .forms import UploadFileForm
from students.forms import ProfilePicUpdateForm

class TeacherTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'teachers/home.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        if not user.is_teacher:
            return HttpResponse('<h1>You are not a teacher</h1>')
        teacher = Teacher.objects.get(user=user)
        examinations = Examination.objects.all()
        context['name'] = teacher.user.get_full_name()
        try:
            subjects = Subject.objects.filter(teacher=teacher)
            context['subjects'] = subjects
        except Subject.DoesNotExist:
            pass
        try:
            class_teacher = ClassTeacher.objects.get(teacher=teacher)
            context['class_teacher'] = class_teacher
        except ClassTeacher.DoesNotExist:
            context['class_teacher'] = ""
        return context

@login_required
def teacher_profile_view(request,slug):
    teacher = Teacher.objects.get(slug=slug)
    subjects = Subject.objects.filter(teacher=teacher)
    return render(request,'teachers/profile.html',{'teacher':teacher,'subjects':subjects})

@login_required
def class_result_update(request,slug):
    subject = Subject.objects.get(slug=slug)
    if request.user != subject.teacher.user:
        return HttpResponse("<h1>You are not allowed to access the given details<h1>")
    students = Student.objects.filter(current_standard=subject.standard).order_by('roll_number')
    examinations = Examination.objects.filter(standard=subject.standard)

    if request.method == 'POST':
        for student in students:
            for examination in examinations:
                exam = examination.name
                result = Result.objects.get(student=student,subject=subject,examination=examination)
                x = str(student.roll_number) + " " + exam.name
                marks = request.POST.get(x)
                try:
                    result.marks_secured = int(marks)
                except:
                    result.marks_secured = None
                result.save()
        return redirect('teachers:home')

    results = {}
    for student in students:
        results[student] = {}
        for examination in examinations:
            try:
                result = Result.objects.get(student=student,subject=subject,examination=examination)
            except Result.DoesNotExist:
                result = Result(student=student,subject=subject,examination=examination)
                result.save()
            results[student][examination] = result

    my_dict = {
        'results':results,
        'subject':subject,
        'students':students,
        'examinations':examinations,
        'size':str(len(examinations))
    }

    return render(request,'teachers/update_result.html',context=my_dict)

@login_required
def upload_file(request):
    form = UploadFileForm(request.POST or None)
    if request.method == 'POST':
        upload_file = request.FILES('document')
        fs = FileSystemStorage()
        fs.save(upload_file.name, upload_file)
    return render(request,'teachers/upload.html',{'form':form})

@login_required
def class_teacher_home(request):
    if not request.user.teacher.class_teacher:
        return HttpResponse("<h1>You are not allowed to access the given details<h1>")
    teacher = request.user.teacher
    students = Student.objects.filter(current_standard=teacher.class_teacher.standard)
    return render(request,'standards/class_teacher_home.html',{'students':students})

@login_required
def student_grade_view(request,slug):
    student = Student.objects.get(slug=slug)
    standard = student.current_standard
    examinations = Examination.objects.filter(standard=standard)
    results = {}
    for examination in examinations:
        results[examination] = Result.objects.filter(student=student,examination=examination).order_by('subject')
    subjects = Subject.objects.filter(standard=standard)
    for result in results[examinations[0]]:
        subjects.append(result.subject)
    dict = {
        'student':student,
        'standard':standard,
        'results':results,
        'examinations':examinations,
        'subjects':subjects
    }
    return render(request,'students/grades.html',dict)

@login_required
def profile_pic_update_view(request):
    user = request.user
    if not user.is_teacher:
        return HttpResponse('<h1>Invalid request</h1>')
    teacher = user.teacher
    if request.method == 'POST':
        form = ProfilePicUpdateForm(request.POST, request.FILES,instance=user)
        form.save()
        return redirect('teachers:profile',slug=teacher.slug)
    form = ProfilePicUpdateForm(instance=user)
    return render(request,'teachers/profile_pic_update.html',{'form':form })

uploads/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required
from .forms import UploadForm
from .models import Upload
from subjects.models import Subject

@login_required
def upload_view(request,slug):
    if not request.user.is_teacher:
        return HttpResponse('<h1>You are not authorised to view this page</h1>')
    subject = Subject.objects.get(slug=slug)
    teacher = subject.teacher
    if teacher.user != request.user:
        return HttpResponse('<h1>You are not authorised to view this page</h1>')
    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
            upload = form.save(commit=False)
            upload.subject = subject
            upload.save()
            return redirect('teachers:upload',slug=subject.slug)
        else:
            print(form.errors)

    else:
        form = UploadForm()
    pdfs = Upload.objects.filter(subject=subject)
    return render(request,'teachers/upload.html',{'form':form,'pdfs':pdfs,'subject':subject})

@login_required
def delete_view(request,slug):
    pdf = Upload.objects.get(slug=slug)
    subject = pdf.subject
    teacher = subject.teacher
    if teacher.user != request.user:
        return HttpResponse('<h1>You are not authorised to view this page</h1>')
    pdf.delete()
    return redirect('teachers:upload',subject.slug)

templates/teachers/base.html
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}
{% load teacher_extras %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Teacher</title>
  <link rel="stylesheet" href="{% static 'teachers/style.css' %}">
  <link rel="stylesheet" href="{% static 'general.css' %}">
  {% block stylesheets %}
  
  {% endblock stylesheets %}
</head>
<body>
  <!-- <img class="logo" src="{% static 'images/fchs.png' %}" alt=""> -->

    <nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-primary">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">Hello {{teacher_cp.user.first_name}} {{teacher_cp.user.second_name}}</a>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">

          <li class="nav-item active">
            <a class="nav-link" href="{% url 'teachers:home' %}">Home <span class="sr-only">(current)</span></a>
          </li>

          <li class="nav-item active dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Update Result
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              {% for subject in subjects_cp %}
                <a class="nav-link dropdown-item" href="{% url 'teachers:update_result' slug=subject.slug %}">{{subject.name|title}} ({{subject.standard}})</a>
              {% endfor %}
            </div>
          </li>

          <li class="nav-item active dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Upload
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              {% for subject in subjects_cp %}
                <a class="nav-link dropdown-item" href="{% url 'teachers:upload' slug=subject.slug %}">{{subject.name|title}} ({{subject.standard}})</a>
              {% endfor %}
            </div>
          </li>

          <li class="nav-item active">
            <a class="nav-link" href="{% url 'teachers:profile' slug=teacher_cp.slug %}">Profile</a>
          </li>
            {% if request.user.teacher.class_teacher %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'teachers:class_teacher_home' %}">My class</a>
            </li>
            {% endif %}

          <li class="nav-item active">
            <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
          </li>
        </ul>
      </div>
    </nav> <br>

  {% block body_block %}
  {% endblock %}

</body>
</html>

templates/teachers/home.html
{% extends 'teachers/base.html' %}
{% block body_block %}

<div class="container jumbotron" style="height: 100%;">
  <h3>You teach: </h3> <br>
  <table class="table table-striped">
  {% for subject in subjects_cp %}
  <tr>
    <td><a class="btn btn-secondary" href="{% url 'teachers:update_result' slug=subject.slug %}">Update Result</a></td>
    <td style="font-size: large; vertical-align: middle;">{{subject.name|title}} to class {{subject.standard}}</td>
    <td><a class="btn btn-warning" href="{% url 'teachers:upload' slug=subject.slug %}">Upload file</a></td>
  </tr>
  {% endfor %}
  </table>
</div>
  
{% endblock %}

templates/teachers/profile.html
{% extends 'teachers/base.html' %}
{% load static %}

{% block stylesheets %}
  <link rel="stylesheet" href="{% static 'students/style.css' %}">
{% endblock %}

{% block body_block %}
  <div class="container profile-box">
      <h4>Teacher Profile</h4>
    <table class="table thead-dark table-hover table-borderless" style="text-align:left">
      <tr>
        <td><strong>Teacher name:</strong></td>
        <td>{{teacher.user.get_full_name}}</td>
      </tr>
      <tr>
        <td><strong>Email:</strong></td>
        <td>{{teacher.user.email}}</td>
      </tr>
      <tr>
        <td><strong>Date of birth:</strong></td>
        <td>{% if teacher.user.date_of_birth %}
              {{teacher.user.date_of_birth}}
            {% endif %}</td>
      </tr>
      <tr>
        <td><strong>Contact no:</strong></td>
        <td>{% if teacher.user.contact_no %}
              {{teacher.user.contact_no}}
            {% endif %}</td>
      </tr>
      <tr>
        <td><strong>Permanent Address:</strong></td>
        <td>{% if teacher.user.address %}
              {{teacher.user.address}}
            {% endif %}</td>
      </tr>
      <tr>
        <td><strong>Currently teaching:</strong></td>
        <td>
          {% for subject in subjects %}
            {{subject|title}} to Standard: {{subject.standard}} <br>
          {% endfor %}
        </td>
      </tr>
      <tr>
        <td><strong>Profile picture:</strong></td>
        {% if teacher.user.profile_pic %}
        <td><img src="{{teacher.user.profile_pic.url}}"
                 alt="No profile pic"
                 style="width:150px; height:150px; margin-bottom:5px"><br>
            <a class="btn btn-primary"
                  href="{% url 'teachers:profile_pic_update' %}"
                  style="margin:auto auto; width:150px;">Update</a>
        {% else %}
        <td>
          <img src="{% static 'images/default_profile_pic.png' %}"
               alt=""
               style="width:150px; height:150px"><br>
          <a class="btn btn-primary"
                  href="{% url 'teachers:profile_pic_update' %}"
                  style="margin:auto auto; width:150px;">Upload</a>
        {% endif %}
               
        </td>
      </tr>
    </table>
    </div>
  </div>
{% endblock %}

templates/teachers/profile_pic_update.html
{% extends 'teachers/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block body_block %}
<hr class='hr-text' data-content="Update Profile Pic"> <br>
<div class="container jumbotron" style="padding: 30px 20px;">
    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{form|crispy}}
      <input class="btn btn-primary btn-block" type="submit" name="submit" value="Update">
    </form>
</div>
{% endblock %}

templates/teachers/update_result.html
{% extends 'teachers/base.html' %}
{% load teacher_extras %}
{% block body_block %}
<hr class='hr-text' data-content="Update Standard {{subject.standard}}: {{subject|title}} Results"> <br>
  <div class="container">
    <form class="result-form" action="" method="post">
      {% csrf_token %}
      <div class="table-responsive-sm">
        <table class="table table-bordered table-hover">
            <thead class="thead-dark">
              <th style="width: 9ch;">Roll no</th>
              <th class="name-cell">Name</th>
              {% for examination in examinations %}
                <th style="width: 4ch;">{{examination.name}}</th>
              {% endfor %}
            </thead>
          {% for student,examination in results.items %}
              <tr>
                <td style="width: 9ch;">{{student.roll_number}}</td>
                <td class="name-cell">
                  {{student.user.first_name}} {{student.user.last_name}}
                </td>
                {% for examination,result in examination.items %}
                  <td style="width: 4ch;">
                    {% with ans=student.roll_number|myConcat:examination.name %}
                      <input type="number"
                              class="marks-input"
                              name="{{ans}}"
                              value="{{result.marks_secured}}" />
                    {% endwith %}
                  </td>
                {% endfor %}
              </tr>
          {% endfor %}
        </table>
        <input class="btn btn-primary" style="margin-left: 50%; width: 150px;" type="submit" name="" value="Upload"/>
      </div>
    </form>
  </div>
{% endblock %}

templates/teachers/upload.html
{% extends 'teachers/base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}

<hr class='hr-text' data-content="Upload File for Standard {{subject.standard}}: {{subject|title}}"> <br>
<div class="container"> 
  <div class="jumbotron" style="padding: 20px 30px;">
    <form class="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{form|crispy}}
      <input type="submit" class="btn btn-primary btn-block" value="Upload">
    </form>
  </div> <br>
  <hr class='hr-text' data-content="Files uploaded"> <br>
    <table class="table thead-dark table-hover table-bordered">
      <tr class="thead-dark">
        <th>Title</th>
        <th>Uploaded at</th>
        <th>Delete</th>
      </tr>
      <tbody>
      {% for pdf in pdfs %}
      <tr>
        <td><a class=""
               href="{{pdf.pdf.url}}"
               style="margin:auto;"
               target="_blank">{{pdf.title}}</a></td>
        <td>{{pdf.timestamp}}</td>
        <td>
          <form class="form"  onSubmit="return confirm('Are you sure you wish to delete?');" action="{% url 'teachers:delete_upload' slug=pdf.slug %}" method="post">
            {% csrf_token %}
            <button class="btn btn-danger" type="submit">Delete</button>
          </form>
        </td>
      </tr>
      {% endfor %}
      {% if pdfs|length == 0 %}
        <tr>
          <td colspan="3">No files uploaded yet!</td> 
        </tr>
      {% endif %}
      </tbody>
    </table>
</div>
{% endblock %}