accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('',views.login_view,name='login'),
    path('logout/',views.logout_view, name="logout")
]

admins/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from calendars import views as cal_views

app_name = "admins"

urlpatterns = [
    path('signup/',views.signup_view,name='home'),
    path('standard_list',views.standard_list_view,name='standard_list'),
    path('student_list/<slug:slug>/',views.student_list_view,name='student_list'),
    path('all_student_list/',views.all_student_list,name='all_student_list'),
    path('all_teacher_list/',views.all_teacher_list,name='all_teacher_list'),
    path('student_update/<slug:slug>/',views.student_update_view,name='student_update'),
    path('teacher_update/<slug:slug>/',views.teacher_update_view,name='teacher_update'),
    path('refresh_standard/<slug:slug>/',views.refresh_standard_view,name='refresh_standard'),
    path('subject_list/<slug:slug>/',views.subject_list_view,name='subject_list'),
    path('subject_update/<slug:slug>/',views.subject_update_view,name='subject_update'),
    path('class_teacher_update/<slug:slug>/',views.class_teacher_update,name='class_teacher_update'),
    path('student_profile/<slug:slug>/',views.student_profile_view,name='student_profile'),
    path('teacher_profile/<slug:slug>/',views.teacher_profile_view,name='teacher_profile'),

    path('calendar/',cal_views.admin_calendar,name='calendar'),
    path('event/new/',cal_views.event,name='event_new'),
    path('event/edit/<slug:slug>/',cal_views.event, name="event_edit"),
    path('event/delete/<slug:slug>/',cal_views.event_delete, name="event_delete"),
    
]

calendars/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'calendars'

urlpatterns = [
    
]

myschool/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('db/', admin.site.urls),
    path('',include('accounts.urls')),
    path('teacher/',include('teachers.urls')),
    path('student/',include('students.urls')),
    path('admin/',include('admins.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from calendars import views as cal_views

app_name = 'students'

urlpatterns = [
    path('home/',views.student_home_view,name='home'),
    path('profile/<slug:slug>/',views.student_profile_view,name='profile'),
    path('gradebook/',views.student_gradebook_view,name='gradebook'),
    path('grades/<slug:slug>',views.student_grades,name='grades'),
    path('profile_pic_update/',views.profile_pic_update_view,name='profile_pic_update'),

    path('calendar/',cal_views.student_calendar,name='calendar'),
    path('event/new/',cal_views.event,name='event_new'),
    path('event/edit/<slug:slug>/',cal_views.event, name="event_edit")
]

calendars/models.py
from django.db import models
from django.urls import reverse
from django.db.models.signals import post_save, pre_save
from accounts.utils import unique_email_slug_generator
from accounts.models import User

class Event(models.Model):
    title = models.CharField(max_length=200)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    broadcast = models.BooleanField(default=False)
    slug = models.SlugField(max_length=210,blank=True,null=True,editable=False)

    @property
    def get_html_url(self):
        url = reverse('students:event_edit', args=(self.slug,))
        return f"<a href={url}> {self.title} (self) </a>"

def slug_generator(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_email_slug_generator(instance)

pre_save.connect(slug_generator,sender=Event)

students/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone

from standards.models import Standard
from accounts.models import User

from django.db.models.signals import pre_save
from accounts.utils import unique_email_slug_generator
# Create your models here.

CASTE_CHOICES = (
    ("BC", "BC"),
    ("OBC", "OBC"),
    ("SC", "SC"),
    ("ST", "ST"),
    ("General", "General"),
    ("Other", "Other"),
)

RELIGION_CHOICES = (
    ("Hindu", "Hindu"),
    ("Muslim", "Muslim"),
    ("Christian", "Christian"),
    ("Other", "Other"),
)

class Student(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    standards = models.ManyToManyField(Standard)
    current_standard = models.ForeignKey(Standard,related_name='Class',on_delete=models.CASCADE,null=True,blank=True)
    roll_number = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True,editable=False)
    updated_at = models.DateTimeField(auto_now=True,editable=False)
    admission_no = models.CharField(max_length=20)
    father = models.CharField(max_length=200)
    slug = models.SlugField(max_length=210,blank=True,null=True,editable=False)
    caste = models.CharField(max_length=20,
                             choices=CASTE_CHOICES,
                             default="General")
    religion = models.CharField(max_length=10,
                                choices=RELIGION_CHOICES,
                                default='Hindu')

    def __str__(self):
        return str(self.user)


def slug_generator(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_email_slug_generator(instance)

pre_save.connect(slug_generator,sender=Student)

    # class Meta:
    #     ordering = []

calendars/forms.py
from django.forms import ModelForm, DateInput, CheckboxInput
from .models import Event

class EventForm(ModelForm):
  class Meta:
    model = Event
    # datetime-local is a HTML5 input type, format to make date time show on fields
    widgets = {
      'start_time': DateInput(attrs={'type': 'datetime-local','placeholder': 'yyyy-mm-ddThh:mm (Ex: 2001-01-31T20:56)'}, format='%Y-%m-%dT%H:%M'),
      'end_time': DateInput(attrs={'type': 'datetime-local','placeholder': 'yyyy-mm-ddThh:mm (Ex: 2001-01-31T20:58)'}, format='%Y-%m-%dT%H:%M'),
      'broadcast': CheckboxInput(attrs={'class':'broadcast'})
    }
    exclude = ('user',)

  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    # input_formats to parse HTML5 datetime-local input to datetime field
    self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
    self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

students/forms.py
from django import forms
from accounts.models import User
from standards.models import Standard
from students.models import Student
from teachers.models import Teacher
from standards.models import ClassTeacher
from django.contrib.auth import authenticate,logout,login

class ProfilePicUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('profile_pic',)

calendars/views.py
from datetime import datetime, timedelta, date
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
import calendar

from .models import *
from .utils import Calendar
from .forms import EventForm

class CalendarView(generic.ListView):
    model = Event
    template_name = 'students/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # use today's date for the calendar
        d = get_date(self.request.GET.get('month', None))

        # Instantiate our calendar class with today's year and date
        cal = Calendar(d.year, d.month, self.request.user)

        # Call the formatmonth method, which returns our calendar as a table
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

@login_required
def student_calendar(request):
    if not request.user.is_student:
        return HttpResponse("<h1>UNAUTHORISED</h1>")
    d = get_date(request.GET.get('month', None))
    cal = Calendar(d.year, d.month, request.user)
    html_cal = cal.formatmonth(withyear=True)
    context={}
    context['calendar'] = mark_safe(html_cal)
    context['prev_month'] = prev_month(d)
    context['next_month'] = next_month(d)
    return render(request,"students/calendar.html",context)

@login_required
def admin_calendar(request):
    if not request.user.is_admin:
        return HttpResponse("<h1>UNAUTHORISED</h1>")
    d = get_date(request.GET.get('month', None))
    cal = Calendar(d.year, d.month, request.user)
    html_cal = cal.formatmonth(withyear=True)
    context={}
    context['calendar'] = mark_safe(html_cal)
    context['prev_month'] = prev_month(d)
    context['next_month'] = next_month(d)
    return render(request,"admins/calendar.html",context)


def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

@login_required
def event(request, slug=None):
    instance = Event()
    if slug:
        type = 'delete'
        instance = Event.objects.get(slug=slug)
        if not request.user.is_admin and instance.user != request.user:
            return HttpResponse("<h1>UNAUTHORISED</h1>")
    else:
        type = None
        instance = Event()

    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        event = form.save(commit=False)
        event.user = request.user
        event.save()
        if request.user.is_admin:
            return redirect('admins:calendar')
        if request.user.is_student:
            return redirect('students:calendar')
    if request.user.is_admin:
        return render(request,'admins/event.html',{'form':form,'type':type,'slug':slug})
    if request.user.is_student:
        return render(request, 'students/event.html', {'form': form,'type':type,'slug':slug})

@login_required
def event_delete(request, slug):
    instance = Event.objects.get(slug=slug)
    if not request.user.is_admin and instance.user != request.user:
        return HttpResponse("<h1>UNAUTHORISED</h1>")

    instance.delete()

    if request.user.is_admin:
        return redirect('admins:calendar')
    if request.user.is_student:
        return redirect('students:calendar')

students/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.views.generic import (TemplateView,ListView,
                                  DetailView, CreateView,
                                  UpdateView, DeleteView)

from students.models import Student
from results.models import Result, Examination
from teachers.models import Teacher
from subjects.models import Subject
from standards.models import Standard
from accounts.models import User
from uploads.models import Upload
from students.forms import ProfilePicUpdateForm

@login_required
def student_home_view(request):
    user = request.user
    if not user.is_student:
        return HttpResponse('<h1>You are not authorised to view this page</h1>')
    student = Student.objects.get(user=user)
    subjects = Subject.objects.filter(standard=student.current_standard)
    uploads = {}
    for subject in subjects:
        uploads[subject] = Upload.objects.filter(subject=subject)
    context = {
        'subjects':subjects,
        'uploads':uploads,
    }
    return render(request,'students/home.html',context)

@login_required
def student_gradebook_view(request):
    user = request.user
    if not user.is_student:
        return HttpResponse('<h1>You are not authorised to view this page</h1>')
    student = Student.objects.get(user=user)
    examinations = Examination.objects.filter(standard=student.current_standard)
    results = {}
    for examination in examinations:
        results[examination] = Result.objects.filter(student=student,examination=examination).order_by('subject')
    subjects = Subject.objects.filter(standard=student.current_standard)
    standards = student.standards.all()
    dict = {
        'student':student,
        'results':results,
        'examinations':examinations,
        'subjects':subjects,
        'standards':standards,
        'standard': student.current_standard
    }
    return render(request,'students/gradebook.html',dict)

@login_required
def student_grades(request,slug):
    user = request.user
    standard = Standard.objects.get(slug=slug)
    if not user.is_student:
        return HttpResponse('<h1>You are not authorised to view this page</h1>')
    student = Student.objects.get(user=user)
    examinations = Examination.objects.filter(standard=standard)
    results = {}
    for examination in examinations:
        results[examination] = Result.objects.filter(student=student,examination=examination).order_by('subject')
    subjects = Subject.objects.filter(standard=standard)
    dict = {
        'student':student,
        'standard':standard,
        'results':results,
        'examinations':examinations,
        'subjects':subjects
    }
    return render(request,'students/grades.html',dict)

@login_required
def student_profile_view(request,slug=None):
    user = request.user
    if slug is None:
        student = user.student
    else:
        student = Student.objects.get(slug=slug)
    return render(request,'students/profile.html',{'student':student})
    
@login_required
def profile_pic_update_view(request):
    user = request.user
    if not user.is_student:
        return HttpResponse('<h1>Invalid request</h1>')
    student = user.student
    if request.method == 'POST':
        form = ProfilePicUpdateForm(request.POST, request.FILES,instance=user)
        form.save()
        return redirect('students:profile',slug=student.slug)
    form = ProfilePicUpdateForm(instance=user)
    return render(request,'students/profile_pic_update.html',{'form':form })


templates/students/base.html
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Student</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
    crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'general.css' %}">
  {% block stylesheets %}
  {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-primary">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#" style="cursor:auto;">Hello, {{student.user.first_name}} {{student.user.last_name}}</a>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'students:home' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'students:calendar' %}">Calendar</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'students:gradebook' %}">Gradebook</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'students:profile' slug=student.slug %}">Profile</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
          </li>
        </ul>
      </div>
    </nav>

  {% block body_block %}
  {% endblock %}

  <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
   crossorigin="anonymous"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
   crossorigin="anonymous"></script> -->
   <script type="text/javascript" src="{% static 'students/students.js' %}">

   </script>
</body>
</html>

templates/students/calendar.html
{% extends 'students/base.html' %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'calendars/style.css' %}">
{% endblock %}

{% block body_block %}
<div class="clearfix">
	<a class="btn btn-info left" href="{% url 'students:calendar' %}?{{ prev_month }}"> Previous Month </a>
	<a class="btn btn-info right" href="{% url 'students:calendar' %}?{{ next_month }}"> Next Month </a>
	<a class="btn btn-info right" href="{% url 'students:event_new' %}"> New Event </a>
</div>
{{ calendar }}
{% endblock %}

templates/students/event.html
{% extends 'students/base.html' %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'calendars/style.css' %}">
<style>
  .broadcast {
    display: None;
  }
</style>
{% endblock %}

{% block body_block %}
  <div class="clearfix">
    <a class="btn btn-info left" href="{% url 'students:calendar' %}"> Calendar </a>
  </div>

  {% if form.errors %}
      {% for field in form %}
          {% for error in field.errors %}
              <div class="alert alert-danger">
                  {{ field.label }} <strong>{{ error|escape }}</strong>
              </div>
          {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
              {{ field.label }} <strong>{{ error|escape }}</strong>
          </div>
      {% endfor %}
  {% endif %}

  <form method="post">
    {% csrf_token %}
    <table class="form form-table">
      {{form}}
      <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
    </table>
  </form>
{% endblock %}

templates/students/gradebook.html
{% extends 'students/base.html' %}
{% load static %}

{% block stylesheets %}
  <link rel="stylesheet" href="{% static 'students/style.css' %}">
{% endblock %}

{% block body_block %}
<br>
<div class="container table-container">
  <div class="table-responsive-sm">
      <hr class='hr-text' data-content="Class {{standard}} - RESULTS"> <br>
    <table class="grade-table table thead-light table-hover table-bordered">
      <tr>
        <th class="name-cell">Examinations</th>
        {% for subject in subjects %}
          <th>{{subject|title}}</th>
        {% endfor %}
      </tr>
      {% for examination,list in results.items %}
      <tr>
        <td class="name-cell">{{examination.name}}</td>
        {% for result in list %}
          {% if result.marks_secured %}
            <td>{{result.marks_secured}}</td>
          {% else %}
            <td>-</td>
          {% endif %}
        {% endfor %}
      </tr>
      {% endfor %}
    </table>
  </div>
</div><br> <br>
<div class="container gb-box">
  <div class="table-responsive-sm">
      <hr class='hr-text' data-content="Past grades"> <br>
    <table class="gb-table table thead-light table-hover table-bordered">
      {% for standard in standards %}
      <tr>
        <td><a class="btn btn-block text-bold blue-color" style="font-size: 20px; back" href="{% url 'students:grades' slug=standard.slug %}">Standard {{standard.name}}</a></td>
      </tr>
      {% endfor %}
    </table>

</div>
{% endblock %}

templates/students/grades.html
<!DOCTYPE html>
{% extends 'students/base.html' %}
{% load teacher_extras %}
{% load static %}

{% block stylesheets %}
  <link rel="stylesheet" href="{% static 'students/style.css' %}">
{% endblock %}

{% block body_block %}
<br>
<div class="container table-container">
  <div class="table-responsive-sm">
      <hr class='hr-text' data-content="Class {{standard}} - RESULTS"> <br>
    <table class="grade-table table thead-light table-hover table-bordered">
      <tr>
        <th class="name-cell">Examinations</th>
        {% for subject in subjects %}
          <th>{{subject|title}}</th>
        {% endfor %}
      </tr>
      {% for examination,list in results.items %}
      <tr>
        <td class="name-cell">{{examination.name}}</td>
        {% for result in list %}
          {% if result.marks_secured %}
            <td>{{result.marks_secured}}</td>
          {% endif %}
        {% endfor %}
      </tr>
      {% endfor %}
    </table>
  </div>
</div>

{% endblock %}

templates/students/home.html
{% extends 'students/base.html' %}
{% load static %}

{% block stylesheets %}
  <link rel="stylesheet" href="{% static 'students/student-home.css' %}">
{% endblock %}

{% block body_block%}
  <br>
  <div class="home-box">
    <div class="announcements">
      <h4 class="profile-headers" id="first">Announcements</h4>
    </div>
    <div class="uploads">
      <h4 class="profile-headers">Uploads</h4>
      <div class="clickAndSee">
      {% for subject,pdfs in uploads.items %}
        <div class="card">
          <div class="card-header">
            <h3 class="btn btn-link"
                style="text-align: center;"
                onclick="view({{forloop.counter}})">{{subject|title}}</h3>
          </div>
          <div id="{{forloop.counter}}" class="collapsableinitial">
            <div data-spy="scroll" class="container panel-body">
              <table id="{{forloop.counter}}table" class="table upload-table thead-dark table-hover table-bordered"
                      style="text-align:center;">
                <thead>
                  <th style="width:40%">Title</th>
                  <th style="">Type</th>
                  <th>Date uploaded</th>
                </thead>
                {% for pdf in pdfs %}
                <tr>
                  <td>
                    <a class=""
                       href="{{pdf.pdf.url}}"
                       target="_blank">{{pdf.title}}</a>
                  </td>
                  <td>{{pdf.type}}</td>
                  <td>{{pdf.timestamp}}</td>
                </tr>
                {% endfor %}
              </table>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

templates/students/profile.html
{% extends 'students/base.html' %}
{% load static %}

{% block stylesheets %}
  <link rel="stylesheet" href="{% static 'students/style.css' %}">
{% endblock %}

{% block body_block%}
  <div class="container profile-box">
    <h4>Teacher Profile</h4>
    <table class="table thead-dark table-hover table-borderless">
      <tr>
        <td><strong>Student name:</strong></td>
        <td>{{student.user.first_name}} {{student.user.last_name}}</td>
      </tr>
      <tr>
        <td><strong>Email:</strong></td>
        <td>{{student.user.email}}</td>
      </tr>
      <tr>
        <td><strong>Permanent Address:</strong></td>
        <td>{% if student.user.address %}
              {{student.user.address}}
            {% endif %}\</td>
      </tr>
      <tr>
        <td><strong>Date of birth:</strong></td>
        <td>{% if student.user.date_of_birth %}
              {{student.user.date_of_birth}}
            {% endif %}</td>
      </tr>
      <tr>
        <td><strong>Father's Name:</strong></td>
        <td>{% if student.father %}
          {{student.father}}
        {% endif %}</td>
      </tr>
      <tr>
        <td><strong>Contact:</strong></td>
        <td>{{student.user.contact_no}}</td>
      </tr>
      <tr>
        <td><strong>Standards:</strong></td>
      </tr>
      <tr>
        <td><strong>Current standard:</strong></td>
        <td>{{student.current_standard}}</td>
      </tr>
      <tr>
        <td><strong>Roll No:</strong></td>
        <td>{{student.roll_number}}</td>
      </tr>
      <tr>
        <td><strong>Caste:</strong></td>
        <td>{{student.caste}}</td>
      </tr>
      <tr>
        <td><strong>Religion:</strong></td>
        <td>{{student.religion}}</td>
      </tr>
      <tr>
        <td><strong>Profile picture:</strong></td>
        {% if student.user.profile_pic %}
        <td><img src="{{student.user.profile_pic.url}}"
                 alt="No profile pic"
                 style="width:150px; height:150px; margin-bottom:5px"><br>
        {% else %}
        <td>
          <img src="{% static 'images/default_profile_pic.png' %}"
               alt=""
               style="width:150px; height:150px"><br>
        {% endif %}
          {% if student.user == request.user %}
               <a class="btn btn-primary"
                  href="{% url 'students:profile_pic_update' %}"
                  style="margin:auto auto; width:150px;">Upload</a>
          {% endif %}
        </td>
      </tr>
      {% if request.user.admin %}
      <tr>
        <td colspan="2" style="text-align: center;">
          <a class="btn btn-success" href="{% url 'admins:student_update' slug=student.slug %}">Update Profile</a>
        </td>
      </tr>
      {% endif %}
    </table>
  </div>
{% endblock %}

templates/students/profile_pic_update.html
{% extends 'students/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block body_block %}
<br>
<hr class='hr-text' data-content="Update Profile Pic"> <br>
<div class="container jumbotron" style="">
    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{form|crispy}}
      <input class="btn btn-primary btn-block" type="submit" name="submit" value="Update">
    </form>
</div>
{% endblock %}